<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ProdutosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('produtos')->insert([
            ['nome' => 'Parachoque Dianteiro', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Capô de Aço', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 2],
            ['nome' => 'Escapamento Esportivo', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 3],
            ['nome' => 'Lanterna Traseira', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 4],
            ['nome' => 'Roda de Liga Leve', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 5],
            ['nome' => 'Retrovisor Elétrico', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Filtro de Óleo', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 6],
            ['nome' => 'Radiador de Motor', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 7],
            ['nome' => 'Bateria 60Ah', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Kit de Embreagem', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 9],
            ['nome' => 'Farol Xenon', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 4],
            ['nome' => 'Suspensão Traseira', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 10],
            ['nome' => 'Alternador', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Pastilhas de Freio', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 11],
            ['nome' => 'Correia Dentada', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 9],
            ['nome' => 'Sensor de Estacionamento', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Amortecedor Dianteiro', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 10],
            ['nome' => 'Faroletes de Neblina', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 4],
            ['nome' => 'Óleo de Motor 5W-30', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 6],
            ['nome' => 'Sistema de Arrefecimento', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 7],
            ['nome' => 'Lâmpadas Halógenas', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 4],
            ['nome' => 'Cinto de Segurança', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 12],
            ['nome' => 'Sistema de Freios a Disco', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 11],
            ['nome' => 'Bomba de Água', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 7],
            ['nome' => 'Correia de Alternador', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 9],
            ['nome' => 'Radiador de Óleo', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 7],
            ['nome' => 'Vela de Ignição', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Filtro de Ar', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 6],
            ['nome' => 'Pneu de Alta Performance', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 5],
            ['nome' => 'Paralama Dianteiro', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Paralama Traseiro', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Painel Frontal', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 2],
            ['nome' => 'Para-brisa Dianteiro', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 3],
            ['nome' => 'Para-brisa Traseiro', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 3],
            ['nome' => 'Porta Dianteira Esquerda', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 2],
            ['nome' => 'Porta Dianteira Direita', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 2],
            ['nome' => 'Porta Traseira Esquerda', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 2],
            ['nome' => 'Porta Traseira Direita', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 2],
            ['nome' => 'Vidro Lateral Dianteiro', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 3],
            ['nome' => 'Vidro Lateral Traseiro', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 3],
            ['nome' => 'Chave de Setas', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 4],
            ['nome' => 'Grade Frontal', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Retrovisor Esquerdo', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Retrovisor Direito', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Motor Completo', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Caixa de Câmbio', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 9],
            ['nome' => 'Parafuso de Roda', 'descricao' => 'Descricao padrao', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 5],
            ['nome' => 'Câmera de Ré', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Sensor de Pressão dos Pneus', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Disco de Freio', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 11],
            ['nome' => 'Câmbio Automático', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 9],
            ['nome' => 'Sistema de Injeção Eletrônica', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Velas de Ignição Iridium', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Sensor de Oxigênio', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Bomba de Combustível', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 7],
            ['nome' => 'Correia Poly-V', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 9],
            ['nome' => 'Coxim do Motor', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 7],
            ['nome' => 'Unidade de Controle do Motor', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Sensor de Fluxo de Ar', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Filtro de Combustível', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 6],
            ['nome' => 'Tubo de Escape', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 3],
            ['nome' => 'Suspensão Pneumática', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 10],
            ['nome' => 'Buzina Elétrica', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Kit de Reparo de Freio', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 11],
            ['nome' => 'Módulo de Ignição', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Sistema de Navegação GPS', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Cinto de Segurança Infantil', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 12],
            ['nome' => 'Airbag Frontal', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 12],
            ['nome' => 'Volante Esportivo', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 5],
            ['nome' => 'Cabo de Vela', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 8],
            ['nome' => 'Mola de Suspensão', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 10],
            ['nome' => 'Painel de Instrumentos', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 2],
            ['nome' => 'Interruptor de Luz de Freio', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 4],
            ['nome' => 'Sensor de Estacionamento Dianteiro', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Câmera 360 Graus', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Lanterna LED', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 4],
            ['nome' => 'Kit de Segurança Rodoviária', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 12],
            ['nome' => 'Suporte de Câmera para Painel', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 1],
            ['nome' => 'Bomba de Direção Hidráulica', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 7],
            ['nome' => 'Rebite de Freio', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 11],
            ['nome' => 'Filtro de Cabine', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 6],
            ['nome' => 'Roda de Aço', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 5],
            ['nome' => 'Parafuso de Cabeçote', 'descricao' => 'Descrição padrão', 'imagem' => 'produtos/placeholder.png', 'grupo_id' => 9],
        ]);
    }
}
